-- ============================================================
-- Tripomonk — Supabase database schema + seed
-- Paste this whole file into Supabase → SQL Editor → Run.
-- Then edit rows in Table Editor and they update in the app.
-- ============================================================

-- ---------- TABLES ----------
create table if not exists treks (
  id          bigint generated by default as identity primary key,
  name        text not null,
  region      text,
  img         text,
  rating      numeric default 4.7,
  reviews     text   default '0',
  level       text   default 'Moderate',     -- Easy | Moderate | Difficult
  days        int    default 5,
  altitude    text,
  distance    text,
  best_time   text,
  price       int    default 0,
  soon        boolean default false,          -- true = "Coming Soon" (not bookable)
  description text,
  sort        int    default 0
);

create table if not exists batches (
  id        bigint generated by default as identity primary key,
  trek_id   bigint references treks(id) on delete cascade,
  label     text,                 -- "18 May – 22 May"
  seats     text,                 -- "Few seats left" / "Available"
  price     int,
  sort      int default 0
);

create table if not exists bookings (
  id         text primary key,    -- TMK-XXXX (generated by the app)
  trek       text,
  name       text,
  date       text,
  pax        int,
  total      int,
  paid       int,
  status     text default 'Confirmed',
  checked_in boolean default false,
  created_at timestamptz default now()
);

create table if not exists enquiries (
  id         bigint generated by default as identity primary key,
  kind       text,                -- gear | permit | activity | notify
  detail     text,
  created_at timestamptz default now()
);

-- ---------- SECURITY (Row Level Security) ----------
alter table treks      enable row level security;
alter table batches    enable row level security;
alter table bookings   enable row level security;
alter table enquiries  enable row level security;

-- Public can READ treks & batches (so the app can show them)
create policy "read treks"   on treks   for select using (true);
create policy "read batches" on batches for select using (true);
-- Public can CREATE bookings & enquiries (so the app can submit them)
create policy "add booking"   on bookings  for insert with check (true);
create policy "read booking"  on bookings  for select using (true);
create policy "add enquiry"   on enquiries for insert with check (true);
-- (Editing treks/prices is done by YOU in the Supabase dashboard, which
--  bypasses RLS — so the public can't change your content.)

-- ---------- SEED (current treks) ----------
insert into treks (name,region,img,rating,reviews,level,days,altitude,distance,best_time,price,soon,description,sort) values
('Kedarkantha','Uttarakhand','https://images.unsplash.com/photo-1513614835783-51537729c8ba',4.8,'1.2k','Easy',5,'12,500 ft','20 km','Dec – Apr',6499,false,'India''s most loved winter snow trek — pine forests, frozen meadows and a sunrise summit. Ideal for first-time snow trekkers.',1),
('Brahmatal','Uttarakhand','https://images.unsplash.com/photo-1644902560705-740850bc47b8',4.7,'860','Moderate',6,'12,250 ft','22 km','Dec – Mar',8999,false,'Ridge walks with grand views of Mt. Trishul and Nanda Ghunti, plus the legendary frozen Brahmatal lake.',2),
('Valley of Flowers','Uttarakhand','https://images.unsplash.com/photo-1756847845343-7a1053567775',4.9,'2.0k','Moderate',6,'14,100 ft','38 km','Jul – Sep',9499,false,'A UNESCO World Heritage site that bursts into hundreds of alpine flowers in the monsoon, paired with Hemkund Sahib.',3),
('Har Ki Dun','Uttarakhand','https://images.unsplash.com/photo-1732510951898-416631a45e35',4.8,'740','Moderate',7,'11,700 ft','44 km','Apr – Jun',10499,false,'The ''Valley of Gods'' — ancient villages, the Swargarohini massif and gentle river-side camps.',4),
('Nag Tibba','Uttarakhand','https://images.unsplash.com/photo-1714744715493-ad89b7ff503e',4.6,'1.5k','Easy',2,'9,915 ft','16 km','Oct – Mar',3499,false,'The perfect weekend trek from Dehradun — summit views of the Bandarpunch range in a single night out.',5),
('Roopkund','Uttarakhand','https://images.unsplash.com/photo-1718429205172-0d91b73ab23c',4.7,'410','Difficult',8,'15,750 ft','53 km','May – Jun',13999,false,'The mysterious skeleton lake — a demanding high-altitude classic for experienced trekkers.',6),
('Hampta Pass','Himachal','https://images.unsplash.com/photo-1644902560705-740850bc47b8',4.7,'890','Moderate',5,'14,100 ft','26 km','Jun – Sep',9999,true,'A dramatic crossover trek from the green Kullu valley to the barren landscapes of Lahaul — a trek of two worlds.',7);

-- Sample batches for Kedarkantha (trek id 1)
insert into batches (trek_id,label,seats,price,sort) values
(1,'18 May – 22 May','Few seats left',6499,1),
(1,'25 May – 29 May','Available',6499,2),
(1,'01 Jun – 05 Jun','Available',6999,3);
